# Site settings
title: Ezzaldeen Mousa
email: ezzaldeenmousa@outlook.com
description: "An attempt to decode my embedded thoughts."
baseurl: ""
url: "https://ezzaldeeen.github.io"
twitter_username: ezzaldeeeen
github_username: ezzaldeeen

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

jekyll_compose:
  default_front_matter:
    posts:
      layout: post
      sub-title: ""
      overview: ""
      abstract: ""
    drafts:
      layout: post
      sub-title: ""
      overview: ""
      abstract: ""
